# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RAILS API DEMONSTRATION
email: jbrilla17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  apis :: yum
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Social Media
twitter_username: j0hn_8ri11a
github_username:  jbcool17
linkedin: johnbrilla
pinterest: jbrilla17

# Build settings
markdown: kramdown
